# Generated by Django 2.0.5 on 2018-05-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='list_books',
            field=models.ManyToManyField(blank=True, to='cart.Book'),
        ),
    ]
